### PR TITLE
feat: update sqlx version to 0.6

### LINKED ISSUE #75: Please consider updating sqlx dependency to 0.6
Please consider updating sqlx to 0.6, it [has some nice updates to its dependencies](https://github.com/launchbadge/sqlx/blob/main/CHANGELOG.md#060---2022-06-16) which might also be relevant to security (chrono and/or time crate, me thinks).

### PR DESCRIPTION
**Pull request by SiddheshKanawade**
Update the sqlx version to 0.6

Fix: https://github.com/casbin-rs/sqlx-adapter/issues/75

### CODE REVIEW

**Comment by hsluoyz** [comment]
@SiddheshKanawade plz fix:

image

**Comment by SiddheshKanawade** [comment]
Closing it to check in forked repository

**Comment by SiddheshKanawade** [comment]
Resolves #75 

@hsluoyz @hsluoyz please review

**Comment by hsluoyz** [comment]
@bk138 plz review

**Comment by bk138** [comment]
> @bk138 plz review

Did a quick basic smoke test in my actix-web-v4.1.0-based backend, seems to work OK. I did _not_ run a thorough test w/ all corner cases.

@SiddheshKanawade you should probably squash those 8 commits into 2 to keep git history clean, but this ultimately is up to @hsluoyz to decide.

**Comment by hsluoyz** [comment]
We can do a squash merge to have only one commit

**Pull request merged**
