### PR TITLE
feat: new_with_pool

### LINKED ISSUE #60: Use with existing connection pool
We're using `sqlx` with Postgres using `PgPool`.

It would be good if we could pass the pool to the `SqlxAdapter` instead of it initiating a new connection by itself.

### PR DESCRIPTION
**Pull request by uran0sH**
fix: #60

### CODE REVIEW

**Comment by hsluoyz** [comment]
@hackerchai

**Comment by hsluoyz** [comment]
@mkpankov plz review.

**Review by mkpankov — APPROVED** [review]

**Comment by hsluoyz** [comment]
@RobotHuang plz fix: https://github.com/casbin-rs/sqlx-adapter/pull/61/checks?check_run_id=2829204202

image

**Comment by hsluoyz** [comment]
@hackerchai @PsiACE plz review.

/cc @GopherJ

**Review by 0x8f701 — APPROVED** [review]

**Review by PsiACE — COMMENTED** [review]
Looks good, please consider adding some comments for explanation

**Review by hackerchai — APPROVED** [review]
lgtm

**Comment by jgrund** [comment]
Hi, Would it be possible to cut a new release with this change?

**Comment by hsluoyz** [comment]
@hackerchai @smrpn can we make a new release? Or even better, can we support semantic-release?

**Comment by hackerchai** [comment]
> Hi, Would it be possible to cut a new release with this change?

@jgrund  see release v0.4.2

**Pull request merged**
